# Generated by Django 3.2.9 on 2021-12-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211202_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
