# Generated by Django 3.2.9 on 2021-12-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_message_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('created',)},
        ),
    ]
